
  
language: julia
sudo: false
os:
  - linux
julia:
  - 1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GlobalSearchRegressionGUI"))'
